const allProducts = [
  {
    id: 1,
    type: "oversized-tshirt",
    image: "https://veirdo.in/cdn/shop/files/05_06.jpg?v=1723287774&width=533",
    title: "Veirdo Blue Oversized Back Graphic Printed Tshirt",
    discountPrice: 549,
    originalPrice: 1199,
    discountText: "54% off",
    bestseller: "yes",
  },
  {
    id: 2,
    type: "oversized-tshirt",
    image:
      "https://veirdo.in/cdn/shop/files/Artboard_14.png?v=1725010011&width=533",
    title: "Punk Beige Oversized",
    discountPrice: 699,
    originalPrice: 1399,
    discountText: "50% off",
    bestseller: "yes",
  },
  {
    id: 3,
    type: "oversized-tshirt",
    image:
      "https://veirdo.in/cdn/shop/files/Artboard_27.png?v=1726318500&width=533",
    title: "Veirdo Original Green Oversized Typography Brand Printed Tshirt",
    discountPrice: 549,
    originalPrice: 1199,
    discountText: "54% off",
    newarrivals: "no",
    centrestage:"yes",
  },
  {
    id: 4,
    type: "oversized-tshirt",
    image:
      "https://veirdo.in/cdn/shop/files/OS_100_VDBFKNOMR_DC.jpg?v=1742294179&width=533",
    title: "VBe Fake Dutch Canal Oversized Graphic Printed Tshirt",
    discountPrice: 549,
    originalPrice: 1199,
    discountText: "54% off",
    newarrivals: "yes",
  },
  {
    id: 5,
    type: "oversized-tshirt",
    image:
      "https://veirdo.in/cdn/shop/files/m-os-100-eye-blk-new-veirdo-original-imaghdwvc4hp3yry.jpg?v=1722683450&width=533",
    title: "Eye Black Oversized Pocket Graphic Printed Tshirt",
    discountPrice: 549,
    originalPrice: 1199,
    discountText: "54% off",
    bestseller: "yes",
  },
  {
    id: 6,
    type: "oversized-tshirt",
    image:
      "https://veirdo.in/cdn/shop/files/Artboard_29.png?v=1726318033&width=533",
    title: "Everything Gonna Be Okay Lilac Oversized Printed Tshirt",
    discountPrice: 549,
    originalPrice: 1199,
    discountText: "54% off",
    bestseller: "yes",
  },
  {
    id: 7,
    type: "oversized-tshirt",
    image: "https://veirdo.in/cdn/shop/files/01_02.jpg?v=1730189513&width=533",
    title: "ALWAYS LONELY AT THE TOP Black Oversized Back Puff Printed Tshirt",
    discountPrice: 549,
    originalPrice: 1199,
    discountText: "54% off",
    newarrivals: "yes",
  },
  {
    id: 8,
    type: "oversized-tshirt",
    image:
      "https://veirdo.in/cdn/shop/files/Black-Spidey-Original-Marvel-Oversized-Tee-Veirdo-7773.jpg?v=1707127141&width=533",
    title: "Spiderman Black Oversized Back Typographic Printed Tshirt",
    discountPrice: 549,
    originalPrice: 1199,
    discountText: "54% off",
    newarrivals: "yes",
  },
  {
    id: 9,
    type: "cargos",
    image:
      "https://veirdo.in/cdn/shop/files/01_0012_plp.jpg?v=1733905700&width=533",
    title: "Beige Bellow Pocket Woven Exclusive Cargo Pant",
    discountPrice: 1499,
    originalPrice: 3999,
    discountText: "63% off",
  },
  {
    id: 10,
    type: "cargos",
    image:
      "https://veirdo.in/cdn/shop/files/01_0007_1.jpg?v=1733905826&width=533",
    title: "Grey Flap Pocket Woven Exclusive Cargo Pant",
    discountPrice: 1499,
    originalPrice: 3999,
    discountText: "63% off",
  },
  {
    id: 11,
    type: "cargos",
    image:
      "https://veirdo.in/cdn/shop/files/01_0002_10.jpg?v=1732873143&width=533",
    title: "Black Flap Pocket Woven Exclusive Cargo Pant",
    discountPrice: 1499,
    originalPrice: 3999,
    discountText: "63% off",
    centrestage: "yes",
  },
  {
    id: 12,
    type: "hoodies",
    image:
      "https://veirdo.in/cdn/shop/files/Artboard_23.png?v=1736573881&width=533",
    title: "World of Illusion Green Back Printed Regular Fit Hoodie",
    discountPrice: 999,
    originalPrice: 2999,
    discountText: "57% off",
    centrestage: "yes",
  },
  {
    id: 13,
    type: "hoodies",
    image: "https://veirdo.in/cdn/shop/files/65.jpg?v=1729754824&width=533",
    title: "Skull Dark Blue Back Graphic Printed Regular Fit Hoodie",
    discountPrice: 999,
    originalPrice: 1999,
    discountText: "50% off",
    centrestage: "no",
  },
  {
    id: 14,
    type: "hoodies",
    image:
      "https://veirdo.in/cdn/shop/files/Artboard_123_1.jpg?v=1729763398&width=533",
    title: "Purple Plain Regular Hoodie",
    discountPrice: 999,
    originalPrice: 1999,
    discountText: "50% off",
    centrestage: "no",
  },
  {
    id: 15,
    type: "hoodies",
    image: "https://veirdo.in/cdn/shop/files/38_1.jpg?v=1729060807&width=533",
    title: "Green Oversized Plain Sweatshirt",
    discountPrice: 799,
    originalPrice: 1999,
    discountText: "60% off",
    centrestage: "no",
    newarrivals:"yes",
  },
  {
    id: 16,
    type: "hoodies",
    image:
      "https://veirdo.in/cdn/shop/files/4_9_489add35-f6ab-4724-9733-dae7522cf507.jpg?v=1735045500&width=533",
    title: "Dark Green Plain Regular Fit Hoodie",
    discountPrice: 999,
    originalPrice: 1999,
    discountText: "50% off",
    centrestage: "yes",
  },
  {
    id: 17,
    type: "hoodies",
    image:
      "https://veirdo.in/cdn/shop/files/47_0da620db-f8d0-4d60-a00d-2bf2a03461c4.jpg?v=1729506781&width=533",
    title: "Integrity Graphic Print Oversized Hooded Sweatshirt",
    discountPrice: 999,
    originalPrice: 2799,
    discountText: "64% off",
    centrestage: "no",
  },
  {
    id: 18,
    type: "hoodies",
    image:
      "https://veirdo.in/cdn/shop/files/51_1_23bf5d9e-3ef1-4cc2-a197-6beccdd3d6aa.jpg?v=1729750441&width=533",
    title: "Beige Solid Regular Hoodie",
    discountPrice: 999,
    originalPrice: 199,
    discountText: "50% off",
    centrestage: "no",
  },
  {
    id: 19,
    type: "hoodies",
    image:
      "https://veirdo.in/cdn/shop/files/40_2.jpg?v=1729766638&width=533",
    title: "Keep Growing Purple Front Printed Regular Fit Sweatshirt",
    discountPrice: 999,
    originalPrice: 199,
    discountText: "50% off",
    centrestage: "no",
  },
];
export default allProducts;
